name: AppConfiguration-DotnetProvider CI

on:
  push:
    branches:
      - main
      - preview
      - release/*
  pull_request:
    branches:
      - main
      - preview
      - release/*

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install .NET
        run: |
          pwsh build/install-dotnet.ps1 -RestoreOnly

      - name: Restore
        run: |
          pwsh build.ps1 -RestoreOnly

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: 'csharp'

      - name: Dotnet Build
        run: |
          pwsh build.ps1

      - name: Dotnet Pack
        run: |
          pwsh pack.ps1

      - name: Dotnet Test
        run: |
          pwsh test.ps1 || exit 0

      - name: Publish Test Results
        uses: actions/upload-artifact@v2
        with:
          name: Unit Test Results
          path: ${{ github.workspace }}/tests/*.trx
