name: AppConfiguration-DotnetProvider CI

on:
  push:
    branches:
      - main
      - preview
      - release/*
  pull_request:
    branches:
      - main
      - preview
      - release/*

permissions:
  security-events: write
  id-token: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install .NET
        run: pwsh build/install-dotnet.ps1 -RestoreOnly

      - name: Restore
        run: pwsh build.ps1 -RestoreOnly

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: 'csharp'

      - name: Dotnet Build
        run: pwsh build.ps1

      - name: Dotnet Pack
        run: pwsh pack.ps1

      - name: Azure Login with OIDC
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    
      - name: Create Subscription Settings File
        shell: pwsh
        run: |
          $subscriptionId = "${{ secrets.AZURE_SUBSCRIPTION_ID }}"
          $jsonContent = @"
          {
            "Success": true,
            "SubscriptionId": "$subscriptionId"
          }
          "@
          Set-Content -Path "./tests/Integration/appsettings.Secrets.json" -Value $jsonContent

      - name: Dotnet Test
        run: pwsh test.ps1

      - name: Publish Test Results
        uses: actions/upload-artifact@v4
        with:
          name: Unit Test Results
          path: ${{ github.workspace }}/tests/**/*.trx

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
